/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface PixelButton {
        "accent": boolean;
        "autofocus": boolean;
        "backgroundColor": string;
        "borderColor": string;
        "color": string;
        "disabled": boolean;
        "flat": boolean;
        "outlined": boolean;
        "primary": boolean;
        "raised": boolean;
        "secondary": boolean;
        "theme": string;
        "uppercase": boolean;
    }
    interface PixelIcon {
        "grayscale": boolean;
        "svg": boolean;
    }
}
declare global {
    interface HTMLPixelButtonElement extends Components.PixelButton, HTMLStencilElement {
    }
    var HTMLPixelButtonElement: {
        prototype: HTMLPixelButtonElement;
        new (): HTMLPixelButtonElement;
    };
    interface HTMLPixelIconElement extends Components.PixelIcon, HTMLStencilElement {
    }
    var HTMLPixelIconElement: {
        prototype: HTMLPixelIconElement;
        new (): HTMLPixelIconElement;
    };
    interface HTMLElementTagNameMap {
        "pixel-button": HTMLPixelButtonElement;
        "pixel-icon": HTMLPixelIconElement;
    }
}
declare namespace LocalJSX {
    interface PixelButton {
        "accent"?: boolean;
        "autofocus"?: boolean;
        "backgroundColor"?: string;
        "borderColor"?: string;
        "color"?: string;
        "disabled"?: boolean;
        "flat"?: boolean;
        "outlined"?: boolean;
        "primary"?: boolean;
        "raised"?: boolean;
        "secondary"?: boolean;
        "theme"?: string;
        "uppercase"?: boolean;
    }
    interface PixelIcon {
        "grayscale"?: boolean;
        "svg"?: boolean;
    }
    interface IntrinsicElements {
        "pixel-button": PixelButton;
        "pixel-icon": PixelIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pixel-button": LocalJSX.PixelButton & JSXBase.HTMLAttributes<HTMLPixelButtonElement>;
            "pixel-icon": LocalJSX.PixelIcon & JSXBase.HTMLAttributes<HTMLPixelIconElement>;
        }
    }
}
